sudo: false

language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer
    - build/cache

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --verbose || travis_terminate 1
  - mkdir -p build/cache && vendor/bin/php-cs-fixer --cache-file=build/cache/.php_cs.cache --diff --dry-run --stop-on-violation --verbose fix

after_success:
  - travis_retry php vendor/bin/coveralls
